
Namespace(batch_size=64, criterion='cross_entropy', data_dir='/opt/ml/input/data/train/images', dataset='MaskBaseDataset', epochs=5, log_interval=20, lr=0.001, lr_decay_step=20, model='BaseModel', model_dir='./model', name='exp', optimizer='Adam', resize=(128, 96), seed=42, transform='BaseTransform', val_batch_size=1000, val_ratio=0.2)
/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Epoch: 1/5 [020/236]
training accuracy: 53.12%	training loss: 2.0109	learning rate: 0.001
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    train(helper=helper)
  File "train.py", line 136, in train
    "Test/loss": val_loss,
UnboundLocalError: local variable 'val_loss' referenced before assignment